FRAME_CAPTURE_INTERVAL_MS = 200
LIVENESS_TIMEOUT_SECONDS = 30

REQUIRED_FACE_COUNT = 1
FACE_WIDTH_MIN_RATIO = 0.18
FACE_WIDTH_MAX_RATIO = 0.88
FACE_CENTER_TOLERANCE = 0.30

# Eye Aspect Ratio (EAR):
# EAR = (||p2-p6|| + ||p3-p5||) / (2 * ||p1-p4||)
# Higher EAR means open eye, lower EAR means closed eye.
EAR_OPEN_THRESHOLD = 0.24
EAR_CLOSED_THRESHOLD = 0.19

MIN_FRAME_SHARPNESS = 20.0
